#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# sanity check
[ -z "${modprobe.blacklist}" ] && exit 0

# write blacklist to modprobe.d
IFS=','
for b in ${modprobe.blacklist}; do
	echo "blacklist $b" >> /etc/modprobe.d/initramfs.conf
done
