#!/bin/sh -e

version="$1"
bootopt=""

# passing the kernel version is required
if [ -z "${version}" ]; then
	echo >&2 "W: initramfs-tools: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
	exit 2
fi

# kernel-package passes an extra arg
if [ -n "$2" ]; then
	if [ -n "${KERNEL_PACKAGE_VERSION}" ]; then
		# exit if custom kernel does not need an initramfs
		if [ "$INITRD" = 'No' ]; then
			exit 0
		fi
		bootdir=$(dirname "$2")
		bootopt="-b ${bootdir}"
	else
		# official Debian linux-images take care themself
		exit 0
	fi
fi

# avoid running multiple times
if [ -n "$DEB_MAINT_PARAMS" ]; then
	eval set -- "$DEB_MAINT_PARAMS"
	if [ -z "$1" ] || [ "$1" != "configure" ]; then
		exit 0
	fi
fi

# we're good - create initramfs.  update runs do_bootloader
update-initramfs -c -t -k "${version}" ${bootopt} >&2
