#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

fstab_files()
{
    echo /etc/fstab
    if [ -d /etc/fstab.d ]; then
        ls -1 /etc/fstab.d | grep '\.fstab$' | sed -e 's;^;/etc/fstab.d/;'
    fi
}

# Find a specific fstab entry
# $1=mountpoint
# $2=fstype (optional)
_read_fstab_entry () {
	# Not found by default.
	echo "MNT_FSNAME="
	echo "MNT_DIR="
	echo "MNT_TYPE="

	fstab_files | while read file; do
		if [ -f "$file" ]; then
			while read MNT_FSNAME MNT_DIR MNT_TYPE MNT_OPTS MNT_FREQ MNT_PASS MNT_JUNK; do
				case "$MNT_FSNAME" in
				  ""|\#*)
					continue;
					;;
				esac
				if [ "$MNT_DIR" = "$1" ]; then
					if [ -n "$2" ]; then
						[ "$MNT_TYPE" = "$2" ] || continue;
					fi
	                                echo "MNT_FSNAME=$MNT_FSNAME"
	                                echo "MNT_DIR=$MNT_DIR"
	                                echo "MNT_TYPE=$MNT_TYPE"
					break 2
				fi
				MNT_DIR=""
			done < "$file"
		fi
	done
}

# Find a specific fstab entry and print its type (if found)
# $1=mountpoint
get_fstype () {
	eval "$(_read_fstab_entry "$1")"

	# Not found by default.
	if [ "$1" = "$MNT_DIR" ]; then
		echo "$MNT_TYPE"
	fi
}

get_fstypes() {
	get_fstype /
	get_fstype /etc
	get_fstype /usr
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

if [ ! -x /sbin/fsck ]; then
	exit 0
fi

. /usr/share/initramfs-tools/hook-functions


copy_exec /sbin/fsck
copy_exec /sbin/logsave
for type in $(get_fstypes | sort | uniq); do
	prog="/sbin/fsck.${type}"
	if [ -h "$prog" ]; then
		link=$(readlink -f "$prog")
		copy_exec "$link"
		ln -s "$link" "${DESTDIR}/$prog"
	else
		copy_exec "$link"
	fi
done
